# Generated by Django 5.2.12 on 2026-03-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dateevents', models.DateField()),
                ('year', models.CharField(blank=True, default=2026, max_length=4, null=True)),
            ],
            options={
                'verbose_name_plural': 'school events',
            },
        ),
    ]
