# Generated by Django 5.2.12 on 2026-03-29 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='todaydate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
