# Generated by Django 5.2.12 on 2026-04-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_attendance_todaydate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'todaydate')},
        ),
    ]
