# Generated by Django 5.2.12 on 2026-04-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
